### ISSUE TITLE
NOTEだよ

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#1]
やること
- サーバーサイドはAPIのみ
- DRYじゃないコピペコードをコントローラーに
- CRUD ほしい
- クライアントサイドもつくる、というか用意しておく。(TODOアプリ的な） backbone.js
- gem にするのは rack ミドルウェア
  - 4xx/5xx のエラーハンドラー的なもの
  - JSONの snake_case / camelCase の変換
- DBは sqlite でOKかな

**Comment by rnakano** [comment]
> - サーバーサイドはAPIのみ

APIのみだと、4xx/5xx のエラーハンドリングをするミドルウェアはどんなのができるんでしょう？

> - DBは sqlite でOKかな

ぼくはOKです。

Webフレームワークは Padrino で fix ですか？

**Comment by junsumida** [comment]
> Webフレームワークは Padrino で fix ですか？

ActiveRecordを使いたいだけなので、Sinatra + ARでも良いかなと思ってます。
ARを使う理由としては、半日程度しか開発する時間がないので、あまりDB層に時間をかけてもらいたくないなというのがあるからです。

**Comment by luckypool** [comment]
> > - サーバーサイドはAPIのみ
> 
> APIのみだと、4xx/5xx のエラーハンドリングをするミドルウェアはどんなのができるんでしょう？

イメージとしては、クライアントサイドでハンドリングできるように json を返すものですかねー
- ミドルウェアない場合
  - 404とか500のレスポンスが json にならなくて、クライアントサイドでハンドリングできない
- ミドルウェアある場合
  -  404とか500でもちゃんとjson が返ってきて、何かあったときでもクライアントサイドでハンドリングできる

**Comment by rnakano** [comment]
> ARは使いたいだけなので、Sinatra + ActiveRecordでも良いかなと思ってます

Padrino をフルスタックで使う場合、学習コストが結構高めなので、Sinatra + AR のほうがいいと思いました。
ARを使うことに異論はないです。実質的にRubyのORマッパーはARしか使われてないですし。

> イメージとしては、クライアントサイドでハンドリングできるように json を返すやつ的な感じですかねー

理解しました！

**Comment by junsumida** [comment]
> Padrino をフルスタックで使う場合、学習コストが結構高め

なるほど、学習コストが上がるのは嫌ですね。では、sinatra + ARにしましょう!
Padrinoにしたのは、作る側がやや楽かなと思ったぐらいなので。

**Comment by luckypool** [comment]
↑の話を踏まえて、さっきMTGをしたった。
Google Drive に写真を置いときました
- http://goo.gl/y2S7Fl
- http://goo.gl/LNwQoI

あとは適宜issue化して取り組んでいきましょうってことで、このissueはクローズしちゃいます。

**Comment by junsumida** [comment]
:+1:
