### ISSUE TITLE
クライアントサイドつくる

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#10]
何かどこかのTODOアプリを少しいじって使うかんじかな？

**Comment by rnakano** [comment]
TODOアプリさがしてきますー

**Comment by rnakano** [comment]
Backbone.js の TODO アプリ（localStorage使用）をREST APIを叩くように作り替えます。
https://github.com/jashkenas/backbone/tree/master/examples/todos

**Comment by junsumida** [comment]
:+1:  なんというイケメン :sunglasses:

**Comment by luckypool** [comment]
(・∀・)ｋｔｋｒ

**Comment by rnakano** [comment]
だいたいできたのでPRします

**Comment by rnakano** [comment]
#12
