### ISSUE TITLE
software 404 -> http status 404的な書き換え問題

### ISSUE THREAD

**Issue by junsumida** [mixi-inc/RubyTraining#17]
#7 の問題内容の候補として

400/404/500的なやつを作ってて思ったのですが、最初に302, 303を返し、redirectで404.htmlに飛ばすエラーハンドラーを作っておいて、返す内容はそのままに、それを404を返すように書き換えなさい的な問題はどうでしょうか。

[SEOの勉強として](http://www.seo-matome.jp/site-structure/404-error-page/)も[HTTPの勉強として](http://www.onflow.jp/cyano/archives/161)も良いかなと思いました。

**Comment by rnakano** [comment]
:+1: 

301/302あたりのSEOの話をするならcanonicalにも触れる必要があって、わりと長い話になるのでSEOは話題に出さなくてもいいかなーと思いました。
問題は良いと思います。

**Comment by junsumida** [comment]
あー、ここでcanonicalは触れたくないですね...。SEOは質問されたら答えるくらいでいいですかね。

**Comment by junsumida** [comment]
#55 で、この辺の問題を作成してます。

**Comment by junsumida** [comment]
こちらmerge済みのためcloseします。

**Comment by luckypool** [comment]
:+1:
