### ISSUE TITLE
コミュニケーション手段を決める

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#3]
gitter が良さそう
- https://gitter.im/

他の研修でも使うなら、プロジェクトネームみたいな名前のOrganizationを作って、
そのチャンネルにみんなjoinしてもらうのが良さそう
- [ ] ↑を他の講師の人に聞いて問題ないか確認する
- [ ] 問題あればPlan B（ChatWork）でやる

**Comment by junsumida** [comment]
:+1:

**Comment by luckypool** [comment]
他の講師・チューターにも意見聞けるようにIRCチャンネルつくった。
あとコンフルにもまとめた。

他の人の意見が特に無いようであれば、こっちて突っ走って決めちゃいたい。

**Comment by junsumida** [comment]
いいですね！ :sunglasses:

**Comment by rnakano** [comment]
:100:

**Comment by luckypool** [comment]
- gitter.im を使う
- メインのチャンネルは、 graduates2014 （みんなコントリビューターになってるやつ）
- 必要に応じて別のチャンネル作ってもOKという感じで
