### ISSUE TITLE
Organization と 研修用リポジトリの作成

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#4]
あと、この現mosscowをtransferする

急ぎじゃないので、 #3 がクローズした後にでも

**Comment by luckypool** [comment]
【緩募】研修のOrganization名

**Comment by junsumida** [comment]
- mixi-noobs :ghost: 
- mixi-newbies
- mixi-freshmen
- mixi-freshers

**Comment by luckypool** [comment]
研修資料は、rubyに限らず https://github.com/mixi-inc に入れることになるかも

**Comment by junsumida** [comment]
お、なるほどー。そっちのほうがお金のコストも管理コストも減るので良いかもしれませんねー。

**Comment by luckypool** [comment]
とりあえず AndroidTraining / iOSTraining とかの兄弟っぽい感じの `RubyTraining` ということで。
なんかずっとオープンしっぱなしなので、クローズしちゃいます。

**Comment by junsumida** [comment]
:+1:
