### ISSUE TITLE
シラバス的なものと時間割

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#5]
ざっくりでいいので作っておく
- [x] 他の講義内容も同じようなテンプレで一覧できるといいのかも

**Comment by luckypool** [comment]
GoogleDriveのシートに追加した
- http://goo.gl/m6rZZF

**Comment by luckypool** [comment]
現状で分かる範囲でやっつけた。
詳細は #6 とか #7 で詰める。

**Comment by rnakano** [comment]
:+1:
