### ISSUE TITLE
Rackのイントロをさくっとgistに

### ISSUE THREAD

**Issue by junsumida** [mixi-inc/RubyTraining#59]
これ的なやつをさくっとまとめて、いい感じにする。
http://rubylearning.com/blog/a-quick-introduction-to-rack/

**Comment by junsumida** [comment]
- WEBサーバーとは http://ja.wikipedia.org/wiki/Web%E3%82%B5%E3%83%BC%E3%83%90
- History of CGI http://en.wikipedia.org/wiki/FastCGI
- miyagawaさんのこれが一番わかりやすい http://gihyo.jp/dev/serial/01/perl-hackers-hub/000101

**Comment by luckypool** [comment]
http://gihyo.jp/dev/serial/01/ruby/0023

ここにも似たような記事が :smiley:

**Comment by luckypool** [comment]
でもなんだかんだ miyagawa-san の方の記事が分かりやすい :confused:

**Comment by junsumida** [comment]
これRackのmiddleware作る時に読みました！ :smiley: 
こっちは実際にRackアプリを作る際に良いかなと思います。

**Comment by luckypool** [comment]
http://junsumida.github.io/mosscow/slides/#/9

とりあえず書いたのでクローズ

**Comment by junsumida** [comment]
あざます！ :smiley:
