### ISSUE TITLE
実習前の基礎的な講義資料

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#6]
- 開発環境の確認とか
- Ruby
  - 2 系になった時の仕様とか？
- Rack
  - Sinatra
- ActiveRecord
- RSpec
  - 3系のbeta との違いについて

---
- [x] 開発環境の確認
- [x] Rubyの復習（チュートリアルやったりしてたら分かるよね？的な）
- [x] TDDとRSpecの話（ describe / it / expectation / matchers ）+ ( pending / xit )
- [x] Rackの話 （概要 / 最小の app → 超絶シンプル middleware ）
- [x] gem / bundler 
- [x] ActiveRecord（概要）

**Comment by luckypool** [comment]
とりあえず markdown でまとめる。
内容によっては reveal.js で書いて gh-pages ブランチに push する。

**Comment by junsumida** [comment]
良いですね！ :smirk:

**Comment by junsumida** [comment]
@luckypool さん、 そもそも論なんですが、テストとはなんぞやとか、spec系のテストの特徴とか触れた方が良いんですかね？

**Comment by luckypool** [comment]
こんな感じの内容を触れるといいのかも？
- [RSpec とは何か](http://magazine.rubyist.net/?0021-Rspec#l6)

**Comment by junsumida** [comment]
↑読んでみましたが、良いですね！ :horse_racing: 
「わかんない人は読んでね！キラッ☆」的な感じでいきましょうか。笑

**Comment by junsumida** [comment]
RSpecの話に`pending`とか`xit`を追加してほしいです！ :baby:

**Comment by rnakano** [comment]
TDDそのものの研修はないみたいなんで、テストとは！みたいな説明あったほうがいいかもですね :snail:

**Comment by luckypool** [comment]
> RSpecの話にpendingとかxitを追加してほしいです！ :baby:

okす！

> TDDそのものの研修はないみたいなんで、テストとは！みたいな説明あったほうがいいかもですね :snail:

そういえばTDDっぽい研修はないですね／(^o^)＼
触れましょう！

**Comment by junsumida** [comment]
`bundler`とか`Gemfile`の説明が必要でした ＼(^o^)／

**Comment by luckypool** [comment]
> bundlerとかGemfileの説明が必要でした ＼(^o^)／

そうでしたね／(^o^)＼

チェックボックスは追加しましたｍｍ

**Comment by junsumida** [comment]
:+1:

**Comment by luckypool** [comment]
開発環境の確認とRubyの復習的なものをスライドにしたった
- http://junsumida.github.io/mosscow/slides

**Comment by rnakano** [comment]
:+1:

**Comment by luckypool** [comment]
引き続き、本日も淡々と作っていきますｍｍ

**Comment by junsumida** [comment]
:+1:

**Comment by luckypool** [comment]
- RSpecの話とRackの話は、ハンズオン形式でやると良さそう
- `hard/app.rb` みたいなものがあったので、同様に独立した `tutorial/app.rb` みたいなものを用意したらいいんじゃないか

**Comment by junsumida** [comment]
いいですね！ :+1:

**Comment by rnakano** [comment]
ディレクトリ分けるのはいいと思います。
`hard/app.rb` はテキトーに切ったので、後でディレクトリ構成を整理したいですね :snail:

**Comment by luckypool** [comment]
> http://junsumida.github.io/mosscow/slides

rspecの話をもりもりしすぎたけど、書いたから追加したった :cyclone: 

> @junsumida さん

#59 で Rackの話がもうあると聞いて :eyes: 
なんかまとまってる markdown 的なものがあればmergeするので教えてくだしあー

**Comment by rnakano** [comment]
rspecに手を動かす演習が入ってるのはとても良いと思います :clap: 

> プロダクトコードの前に先ずテストコードを書き、失敗することを確認する
> テストに成功するようプロダクトコードを書く
> テストに失敗しないようリファクタリング

この説明と実習でやるTDDが一致してないのが気になりました。（リファクタリングしてない）
あと、この段階の Calculator クラスの実装は以下になるはず。

``` ruby
class Calculator
  def add(a,b)
    5
  end
end
```

TDDの講義じゃないから細かいことはスルー！っていうならスルーしてください :snail:

**Comment by junsumida** [comment]
@luckypool さん、特にまだ #59 は手をつけてなかったですー :ghost:

**Comment by luckypool** [comment]
@rnakano さん、あざます！！
そういえばリファクタリングしてなかったすね。取り入れます :+1: 

@junsumida さん、了解です :+1: 
淡い期待でした :ghost:

**Comment by luckypool** [comment]
> http://junsumida.github.io/mosscow/slides

スライド更新
- リファクタリング出来るようにちょっと修正 76f55a3951ab113451b64f9e4b54ca0f0fda1ffa
- gem/bunlderの説明スライド追加 11b49f0140f215bcf2fa7761083e30000eb4cd83

**Comment by rnakano** [comment]
いやらしい指摘をします :smiling_imp: 

`return 5` を `return a + b` へ書き換えるのはリファクタリングじゃないと思います。

`return 5` は十分きれいなのでリファクタリングする必要はないです :snail: 
この段階で次にすべきなのはテストを追加して一度Redにすることで、例えば以下みたいなテストを追加して：

``` ruby
describe Calculator do
  let(:calc) { Calculator.new }
  describe "#add" do
    context "when arguments 2 and 3" do
      it { expect(calc.add(2,3)).to eq 5 }
    end

    context "when arguments 1 and 2" do
      it { expect(calc.add(1,2)).to eq 3 }
    end
  end
end
```

Green にするために実装して：

``` ruby
class Calculator
  def add(a, b)
    return 5 if a == 2 and b == 3
    return 3 if a == 1 and b == 2
  end
end
```

リファクタリングする：

``` ruby
class Calculator
  def add(a, b)
    a + b
  end
end
```

という流れなんじゃないかなと思いました。（この例だと冗長ですが

**Comment by luckypool** [comment]
確かにいやらしい :smirk: 

`add` は比較的シンプルな機能のメソッドなので、
リファクタリングとなると、冗長になっちゃいますね :confused: 

ちょっと良い例を考えてみます :neckbeard:

**Comment by luckypool** [comment]
よさ気なの見つけた。これっぽくしてみる :smiley: 
- http://www.peterprovost.org/blog/2012/05/02/kata-the-only-way-to-learn-tdd
- http://osherove.com/tdd-kata-1/
- http://vimeo.com/7961506

**Comment by junsumida** [comment]
良いですね！ :+1:

**Comment by luckypool** [comment]
> http://junsumida.github.io/mosscow/slides/#/7

TDDのチュートリアルを手厚くしてみた e60a484fdd712ace1b9bafd41b572f79d7343dcb

**Comment by rnakano** [comment]
この図が見たかったんです！！
http://junsumida.github.io/mosscow/slides/#/7/5

:100: :100: :100:

**Comment by junsumida** [comment]
わろたww

**Comment by luckypool** [comment]
http://junsumida.github.io/mosscow/slides

ひと通りスライドにした（細かい修正や、午後の問題の導入的なものは別途必要）

ということでクローズしちゃう！

**Comment by junsumida** [comment]
ActiveRecordとRackが結構な量になってるww すごい :+1:
