### ISSUE TITLE
実習内容と提出内容、追加課題を説明する資料

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#7]
- [x] 実習内容と提出内容
  - これはコードを実際につくってみてだんだん決めてく
  - 指定の結合テストをパスするアプリを作ればOK？
  - コード内容はなんとなく見るくらい？
  - 早く終る人は機能追加してもらう（ユーザー認証など）やり方は自由。
- [x] gem化の手ほどき
  - rackのミドルウェアを作ってgemにしてもらう際、基本的なhow toはテキスト(.md)にまとめてておき、参照してもらう
- [x] 追加課題
  もう既にヤバイ怖い人でもご満足頂ける課題をなんか用意する

**Comment by rnakano** [comment]
#65 で怖い人向けの課題を追加

**Comment by luckypool** [comment]
gem化の手ほどきは http://localhost:9292/problems#h3-4 のヒントのリンク先を参照してもらう

最小限は用意したということでひとまずOK。必要であれば document 用意する。

**Comment by luckypool** [comment]
とりあえず、最小限つくっておいた。

http://junsumida.github.io/mosscow/slides/#/12
- 参加者は基本 fork（ないし自分のリポジトリにpush）してもらう
- 提出は各々の problem ブランチに差分を push してもらう

更に詳細を加えるのであれば、スライドというよりも問題ページにも追記したほうがよさそう
　→　http://localhost:9292/problems

**Comment by luckypool** [comment]
とりあえずクローズでいいかな＼(^o^)／

**Comment by junsumida** [comment]
:+1:
