### ISSUE TITLE
テストを全部expectで書き直す

### ISSUE THREAD

**Issue by junsumida** [mixi-inc/RubyTraining#72]
ワンライナー以外は全部`expect`を使って。書き直す。

**Comment by junsumida** [comment]
#71 でproblemsは修正できますが
- [x] rack-camel_snake
- [x] rack-serer_errors
- [x] master branchの修正が必要です。

**Comment by junsumida** [comment]
#73 で`master`に関しては修正済。

**Comment by junsumida** [comment]
#71 がmergeされたらクローズする

**Comment by luckypool** [comment]
tag が 事務仕事 でワロタ

**Comment by junsumida** [comment]
これは事務仕事です！(`・ω・´)キリッ
