### ISSUE TITLE
研修の日までに終わらせる事務仕事

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#74]
リストアップしてみる
- [x] #7 で残りの資料をやっつける（あとちょっと）
- [x] gh-pages ブランチのスライドを master にもmergeする
  - しなくてもいいけど、なんか master とかけ離れてるのアレなので
  - squash とかでまとめてmergeしちゃうのが良いかな
- [x] README.md を 概要と目次っぽくする
  - 研修のスライドへのリンク
  - プロジェクト自体のドキュメントへのリンク
- [x] RubyTraining という名前で mixi-inc に transfer する
- [x] スライド内容の微修正
  - ex.) ActiveRecordの解説がチュートリアルじゃないので、「コードで解説」的なニュアンスにする

**Comment by junsumida** [comment]
class名とかもmosscowになってるので、併せて直したいですねー

**Comment by luckypool** [comment]
・・・！　そういえば mosscow :open_mouth:

**Comment by luckypool** [comment]
problems ブランチと master ブランチ が結構別物なので
class 名はそのままでもいいかなーっと思ってきた（もし手間だったら）。

あと、リポジトリ名変更　→　transfer が良さそうね。

**Comment by luckypool** [comment]
transfer は done

**Comment by junsumida** [comment]
:+1:

**Comment by junsumida** [comment]
@luckypool さんチェック済なので、クローズします。

**Comment by luckypool** [comment]
:congratulations:
