### ISSUE TITLE
サーバーサイド（good）

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#8]
正解例つくる

サーバーサイドのコード、テスト、gem

**Comment by junsumida** [comment]
とりあえず、sinatraで置き換えるのやりますー。

まず必要そうなTODOs
- [x] sinatraで置き換え
- [x] Active Record入れる
- [x] rspec入れる
- [x] travis再連携

**Comment by junsumida** [comment]
#11 で以上については、done。

**Comment by junsumida** [comment]
以下やります。
- [x] rspecのテストをそれっぽく書く
- [x] post時のparamsのvalidation
- [x] rspecのpost 異常系のテスト

**Comment by junsumida** [comment]
あとこの辺ですかね？ どなたかやってくれていいんですよ！ :ghost: 
- [x] ActiveRecordと連携 #22 で吉池さんが
- [x] backboneと実際に連携しているのかのチェック
- [x] seedでsampleのtodoを生成
- [x] snake <-> camel変換のためのプロパティ名変更 or 追加 #20 #22
- [x] 404/500用のstaticなページ追加 #18 
- [x] 404/500エラー用ミドルウェアのための、絶対に落ちるendpoint追加 #18 
- [x] #14 あたりで先に織り込んでしまったコピペコードのリファクタリング (validationの切り出し？) #42

**Comment by luckypool** [comment]
**NOTE** : まずこのissueをやっつけたあとに、 #9 (bad) の方に取りかかりましょう。

**Comment by junsumida** [comment]
- [x] json変換用の rack middleware切り出し #32
- [x] ミドルウェアのリファクタリング #38 
- [x] エラーハンドラー用のrack middleware切り出し #40 
- [x] 結合テストの追加 `spec/integration/*`とかで良いですかね？ #43

**Comment by junsumida** [comment]
ここでタスク出ししたものは、一通り終わったので、クローズします。

**Comment by rnakano** [comment]
:+1:

**Comment by luckypool** [comment]
:100:
