### ISSUE TITLE
リポジトリのサブタイトル

### ISSUE THREAD

**Issue by junsumida** [mixi-inc/RubyTraining#80]
Ruby Training course for new employees とか？

**Comment by junsumida** [comment]
@luckypool さん、 owner権限がないといけないようなので、よろしくお願いします :stuck_out_tongue_closed_eyes:

**Comment by luckypool** [comment]
こうですか！ (saveしてみた)

**Comment by junsumida** [comment]
Amazing :exclamation: :clap:
