### ISSUE TITLE
スライドの校閲

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#83]
#76 に関連

**Comment by luckypool** [comment]
http://mixi-inc.github.io/RubyTraining/slides/#/6/7

`bundle` じゃなくて `budnel` になってる

他にもありそうだし、あとで grep したい

**Comment by luckypool** [comment]
http://mixi-inc.github.io/RubyTraining/slides/#/10/1

`簡単チュートリアル` → `コードベースで紹介`

くらいにする。チュートリアルっぽくないので。

**Comment by luckypool** [comment]
なおしたのでクローズ

**Comment by rnakano** [comment]
:+1:
