### ISSUE TITLE
サーバーサイド（bad）

### ISSUE THREAD

**Issue by luckypool** [mixi-inc/RubyTraining#9]
アンチパターンなやつをつくっていく

 #8 をまずやってみてから考える感じで

**Comment by luckypool** [comment]
だいたい good の方ができたので、 bad の方に取り掛かりたいす
- このmosscowリポジトリは good のまま残しておく
- bad のほうは fork して汚していく

という感じですかね？

**Comment by junsumida** [comment]
とりあえず、 @luckypool さんか @rnakano さんのとこでforkしてもらって、作るのが早いかなとおもいました :hand: それか、bitbucketでも良いですねー :+1:

**Comment by rnakano** [comment]
個人的には、forkよりブランチのほうがいいと思います。
将来的にこのリポジトリをtransferするなら、リポジトリは1つのほうが管理しやすいからです。

**Comment by rnakano** [comment]
もちろん受講者に正解のコードが見えてしまうという問題はあるけど、厳密な試験じゃないし別にいいのかなと :snail:

**Comment by luckypool** [comment]
> もちろん受講者に正解のコードが見えてしまうという問題はあるけど、厳密な試験じゃないし別にいいのかなと :snail:

確かにそうね :smiley:

**Comment by junsumida** [comment]
ゆるふわな感じですね。 :sheep:  管理コスト下がるのでそうしましょうか :+1:

**Comment by junsumida** [comment]
`problems`ブランチを作成したので、そこにpull-req送る感じですかね？

**Comment by rnakano** [comment]
masterブランチに更新があった場合、upstreamingってします？
追いかけるのだいぶ大変な気がします。

**Comment by junsumida** [comment]
むー。最初は追っかけるの簡単だと思うのですが、時間とともに難しくなると思うので、最初は普通に差分mergeしておいて、面倒な感じになってきたら別に差分作る感じかなーと思いました。

**Comment by luckypool** [comment]
`master` と `problems` は袂を分かちあったbranchですが、基本的には`problems`は独立して汚れていってOKじゃないすかねー

`master`の方にもし変更があっても良い方に変更があるはずで、根本的な変更は無いと思うので、`problems`は`master`の変更を追っかける必要はないのかなと、思いました！

**Comment by junsumida** [comment]
話をぶった切って、bad案
- 全部 `POST` Methodで通信、エンドポイントが`add_todo`とか`delete_todo`とかになってる
- とりあえずmiddlewareはapp.rbの中に全部戻す
- helper使わない
- before/afterも使わない
- `sinatra-contrib`なんてもってのほか
- テストをどこまで残すか悩む

**Comment by rnakano** [comment]
> masterの方にもし変更があっても良い方に変更があるはずで、根本的な変更は無いと思うので、 problemsはmasterの変更を追っかける必要はないのかなと、思いました！

OKです！　追いかけないでいきましょう！

> テストをどこまで残すか悩む

コードは汚くてもテストは残しておくべきだと思いますねー。
ただ、rubocopは除いてもいいかも？　初学者にはちょっと辛そう（rubocop対応ばかりでコードが書けなさそう）

**Comment by junsumida** [comment]
> ただ、rubocopは除いてもいいかも？　初学者にはちょっと辛そう

ですねー。入れたい人は入れれば良いと思うので、Rakefileから抜いておいて、Readmeに「入れたい人はどうぞ」みたいな感じでインストラクションを書いておけばいいかなーと思いました。

**Comment by luckypool** [comment]
> > ただ、rubocopは除いてもいいかも？　初学者にはちょっと辛そう
> 
> ですねー。入れたい人は入れれば良いと思うので、Rakefileから抜いておいて、Readmeに「入れたい人はどうぞって」書いておけばいいかなーと思いました。

いいと思います :+1:

**Comment by rnakano** [comment]
:+1:

**Comment by junsumida** [comment]
デフォルトブランチを`problems`に切り替えました。

**Comment by junsumida** [comment]
rubocopの件は #54 で :sleepy:

**Comment by junsumida** [comment]
@rnakano さん、
#55 をやってて思ったのですが、テストはそのままで良いですかね？

**Comment by junsumida** [comment]
どうしてもTravis落ちると思うので、無視してmergeしてもらう感じになってしまいますが。

**Comment by rnakano** [comment]
ああ、テストそのままっていう意味は、テストカバレッジは維持くらいの意味でした。
なので本体のコードを書き換えた時はそれに合わせてテストも書き換えるべきだと思います。

**Comment by junsumida** [comment]
テストはそのままの方が、問題解きやすいかなーと思ったのですが？ 難易度をどの辺に設定するのが良いんですかねー。
ただまあ、integration testに関しては、普通に通ってて欲しいですね。

**Comment by luckypool** [comment]
研修時に問題の意図が分かりにくくならなければ、テストも修正してOKかもしれません。
例えば、問題文が下記のように用意されていれば・・！

> 問題 No. XXX
> 現状 xxx となっている部分を yyy にしましょう。
> 
> ヒント:
> 既存のテストコードは下記の様になっています
> 
> ```
>  # ...
>  # Current test codes
>  # ...
> 
> ```
> 
> 上記を下記のように書き換えて、テストが通るように ruby コードを修正して下さい
> 
> ```
>  # ...
>  # Expecting better test codes
>  # ...
> 
> ```

難易度は低くなってしまいますが、初学者以外はノーヒントでやってもらう感じですかね？
( or ヒントは wiki とか別ページにリンクさせるとか。ちょっと手間ですが。）

**Comment by junsumida** [comment]
つい、試験的な考え方をしてしまう...。 :astonished: 
htmlで問題ページを作成してリポジトリに入れておけばよいかなと思いました、ヒントはJSでごにょる的な。  基本的にmarkdownで書いておいて、html に出力すれば、作成もそんなに難しくなさそうですし。　:smirk:

**Comment by junsumida** [comment]
#55 でSinatra側で問題をレンダリングするようにしました。見た目と通常時ヒントが隠れるようにしないといけないですが、とりあえずこんな感じで。

**Comment by junsumida** [comment]
#58 でServerErrorsを悲惨な感じに戻しました。

**Comment by luckypool** [comment]
なんかひと通り問題もつくったし、
たぶん実習時間的にも丁度良いような気がするので、
この issue はクローズでOKすかね？ :smiley: 

@junsumida さん、もし問題なければローズしちゃってください :+1:

**Comment by luckypool** [comment]
あ、 #63 くらいが残ってる感じですかねー。

**Comment by junsumida** [comment]
ですね！
#71 ( == #63 ) で比較的大きめの差分が入るので、それがmergeされたらですかね。

**Comment by junsumida** [comment]
#71 #63 が完了したので、閉じます！

**Comment by luckypool** [comment]
:white_flower:
